//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Okhta_Park.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogInSystem
    {
        public int id { get; set; }
        public int id_CodeEmployee { get; set; }
        public System.DateTime LastEntry { get; set; }
        public string InputType { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
