//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Okhta_Park.bd
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class okhta_parkEntities : DbContext
    {
        public okhta_parkEntities()
            : base("name=okhta_parkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<LogInSystem> LogInSystem { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<ServicesOrders> ServicesOrders { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
