//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Okhta_Park.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicesOrders
    {
        public int idServiceOrder { get; set; }
        public int Id_Order { get; set; }
        public int Services { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual Services Services1 { get; set; }
    }
}
